In [26]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv('Downloads/customer.csv')

In [28]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [29]:
df = df.iloc[:,2:]

In [30]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [33]:
X_train

review education
16     Poor        UG
5   Average    School
26     Poor        PG
31     Poor    School
22     Poor        PG
24  Average        PG
19     Poor        PG
2      Good        PG
27     Poor        PG
47     Good        PG
10     Good        UG
6      Good    School
41     Good        PG
15     Poor        UG
42     Good        PG
0   Average    School
44  Average        UG
20  Average    School
17     Poor        UG
29  Average        UG
32  Average        UG
36     Good        UG
46     Poor        PG
35     Poor    School
12     Poor    School
21  Average        PG
8   Average        UG
28     Poor    School
3      Good        PG
7      Poor    School
38     Good    School
14     Poor        PG
34  Average    School
4   Average        UG
33     Good        PG
49     Good        UG
1      Poor        UG
40     Good    School
39     Poor        PG
13  Average    School

In [34]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [35]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [36]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [37]:
X_train

array([[0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.]])

In [38]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [39]:
X_train

array([[0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.]])

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
le = LabelEncoder()

In [42]:
le.fit(y_train)

LabelEncoder()

In [43]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [44]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [45]:
y_train

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])